### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by xycui** [xycui/libresamplesharp#2]

**Comment by morrme** [comment]
which license?

**Comment by xycui** [comment]
@morrme 
1. I am wondering if I take libresample4j as reference and that project is using LGPL2.1 should I also use LGPL or I can use some other license?
2. Should I also add the lisence info in the header comments of the source code? If I need add what kind of comments style should I use?
3. Beside of adding the right License.txt into the project root path, is there any other action I should do?

Thanks in advance.

**Comment by morrme** [comment]
I am not 100 % sure but from other projects that fork or use libraries , the licenses aren't always the same. 

When you add a new file here in GitHub, and name it LICENSE.txt, github should automatically detect this and ask if you'd like to add a license from an existing template. 
![image](https://cloud.githubusercontent.com/assets/26514778/26710527/189e2b00-4720-11e7-9cb8-9085eee57ab4.png)

That should be it, but you can also add a line in the README with license info , and you can add a license badge as well, if you would like.

**Comment by xycui** [comment]
Ok. I will have a try. Thanks a lot.
